"""
Cohort Analysis — tracks how lead cohorts convert over 12 months.

Cohort types:
    - Acquisition month (MQL month)
    - First-touch channel
    - ICP score tier (High/Medium/Low)

Run: python -m src.cohort_analysis
"""
import os, sys, sqlite3
import pandas as pd
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config

COHORT_SQL = """
-- ==========================================================================
-- 04_cohort_analysis.sql
-- Cohort-based conversion and retention analysis.
-- ==========================================================================

-- --------------------------------------------------------------------------
-- Query 1: Monthly Acquisition Cohort Conversion Heatmap
-- Rows = MQL month, Columns = months since MQL (0-12)
-- Values = cumulative conversion rate to each stage.
-- --------------------------------------------------------------------------
WITH mqls AS (
    SELECT
        contact_id,
        account_id,
        SUBSTR(mql_date, 1, 7)          AS cohort_month,
        mql_date,
        sql_date,
        sal_date,
        opportunity_date,
        closed_date,
        lead_status
    FROM contacts
    WHERE mql_date IS NOT NULL
),
cohort_base AS (
    SELECT
        cohort_month,
        COUNT(*)                                                        AS cohort_size,
        SUM(CASE WHEN sql_date IS NOT NULL THEN 1 ELSE 0 END)           AS converted_sql,
        SUM(CASE WHEN opportunity_date IS NOT NULL THEN 1 ELSE 0 END)   AS converted_opp,
        SUM(CASE WHEN lead_status = 'Closed_Won' THEN 1 ELSE 0 END)    AS converted_won
    FROM mqls
    GROUP BY cohort_month
),
month_breakdown AS (
    SELECT
        m.cohort_month,
        CAST((JULIANDAY(m.sql_date) - JULIANDAY(m.mql_date)) / 30 AS INT) AS months_to_sql,
        CAST((JULIANDAY(m.opportunity_date) - JULIANDAY(m.mql_date)) / 30 AS INT) AS months_to_opp,
        CAST((JULIANDAY(m.closed_date) - JULIANDAY(m.mql_date)) / 30 AS INT) AS months_to_won
    FROM mqls m
    WHERE m.sql_date IS NOT NULL
)
SELECT cb.cohort_month, cb.cohort_size,
       ROUND(1.0 * cb.converted_sql / NULLIF(cb.cohort_size, 0), 4)  AS sql_conversion_rate,
       ROUND(1.0 * cb.converted_opp / NULLIF(cb.cohort_size, 0), 4)  AS opp_conversion_rate,
       ROUND(1.0 * cb.converted_won / NULLIF(cb.cohort_size, 0), 4)  AS won_conversion_rate
FROM cohort_base cb
ORDER BY cohort_month;

-- --------------------------------------------------------------------------
-- Query 2: Channel Cohort Comparison
-- Conversion rates by first-touch channel over 12 months.
-- --------------------------------------------------------------------------
WITH first_touch AS (
    SELECT contact_id,
           channel AS first_channel
    FROM (
        SELECT contact_id, channel,
               ROW_NUMBER() OVER (PARTITION BY contact_id ORDER BY touchpoint_timestamp) AS rn
        FROM touchpoints
    ) WHERE rn = 1
)
SELECT
    ft.first_channel                                                    AS channel,
    COUNT(DISTINCT c.contact_id)                                        AS cohort_size,
    COUNT(DISTINCT CASE WHEN c.mql_date  IS NOT NULL THEN c.contact_id END) AS mql_count,
    COUNT(DISTINCT CASE WHEN c.sql_date  IS NOT NULL THEN c.contact_id END) AS sql_count,
    COUNT(DISTINCT CASE WHEN c.opportunity_date IS NOT NULL
                        THEN c.contact_id END)                          AS opp_count,
    COUNT(DISTINCT CASE WHEN c.lead_status = 'Closed_Won'
                        THEN c.contact_id END)                          AS won_count,
    ROUND(1.0 * COUNT(DISTINCT CASE WHEN c.mql_date IS NOT NULL
                                    THEN c.contact_id END)
          / NULLIF(COUNT(DISTINCT c.contact_id), 0), 4)                 AS mql_rate,
    ROUND(1.0 * COUNT(DISTINCT CASE WHEN c.lead_status = 'Closed_Won'
                                    THEN c.contact_id END)
          / NULLIF(COUNT(DISTINCT CASE WHEN c.opportunity_date IS NOT NULL
                                       THEN c.contact_id END), 0), 4)   AS win_rate
FROM contacts c
LEFT JOIN first_touch ft ON ft.contact_id = c.contact_id
WHERE ft.first_channel IS NOT NULL
GROUP BY ft.first_channel
ORDER BY won_count DESC;

-- --------------------------------------------------------------------------
-- Query 3: Cohort Revenue Analysis
-- Revenue generated by each acquisition month cohort + payback period.
-- --------------------------------------------------------------------------
WITH cohort_revenue AS (
    SELECT
        SUBSTR(c.mql_date, 1, 7)       AS cohort_month,
        COUNT(DISTINCT c.contact_id)    AS cohort_size,
        SUM(CASE WHEN o.closed_won = 1 THEN o.amount ELSE 0 END) AS total_revenue,
        AVG(CASE WHEN o.closed_won = 1 THEN o.amount END)        AS avg_deal_size,
        COUNT(DISTINCT CASE WHEN o.closed_won = 1
                            THEN c.contact_id END)                AS won_contacts
    FROM contacts c
    LEFT JOIN opportunities o ON o.primary_contact_id = c.contact_id
    WHERE c.mql_date IS NOT NULL
    GROUP BY SUBSTR(c.mql_date, 1, 7)
)
SELECT
    cohort_month,
    cohort_size,
    total_revenue,
    ROUND(avg_deal_size, 0)            AS avg_deal_size,
    won_contacts,
    ROUND(1.0 * total_revenue / NULLIF(cohort_size, 0), 0) AS revenue_per_lead,
    SUM(total_revenue) OVER (ORDER BY cohort_month ROWS UNBOUNDED PRECEDING) AS cumulative_revenue
FROM cohort_revenue
ORDER BY cohort_month;

-- --------------------------------------------------------------------------
-- Query 4: Cohort Retention Curve
-- % of each cohort with at least one touchpoint in subsequent months.
-- --------------------------------------------------------------------------
WITH mql_cohorts AS (
    SELECT c.contact_id,
           SUBSTR(c.mql_date, 1, 7) AS cohort_month
    FROM contacts c
    WHERE c.mql_date IS NOT NULL
),
monthly_activity AS (
    SELECT t.contact_id,
           SUBSTR(t.touchpoint_timestamp, 1, 7) AS activity_month
    FROM touchpoints t
    GROUP BY t.contact_id, SUBSTR(t.touchpoint_timestamp, 1, 7)
)
SELECT
    mc.cohort_month,
    ma.activity_month,
    CAST((JULIANDAY(ma.activity_month || '-01') -
          JULIANDAY(mc.cohort_month || '-01')) / 30 AS INT) AS months_since,
    COUNT(DISTINCT mc.contact_id) AS cohort_size,
    COUNT(DISTINCT CASE WHEN ma.contact_id IS NOT NULL
                        THEN mc.contact_id END)             AS active_contacts,
    ROUND(1.0 * COUNT(DISTINCT CASE WHEN ma.contact_id IS NOT NULL
                                    THEN mc.contact_id END)
          / NULLIF(COUNT(DISTINCT mc.contact_id), 0), 4)   AS retention_rate
FROM mql_cohorts mc
LEFT JOIN monthly_activity ma ON ma.contact_id = mc.contact_id
    AND ma.activity_month >= mc.cohort_month
GROUP BY mc.cohort_month, ma.activity_month
HAVING months_since BETWEEN 0 AND 12
ORDER BY mc.cohort_month, months_since;
"""

# ---------------------------------------------------------------------------
# Python cohort calculations
# ---------------------------------------------------------------------------

def build_acquisition_cohorts(conn) -> pd.DataFrame:
    sql = """
    SELECT SUBSTR(mql_date,1,7) AS cohort_month,
           COUNT(*) AS cohort_size,
           SUM(CASE WHEN sql_date IS NOT NULL THEN 1 ELSE 0 END) AS sql_count,
           SUM(CASE WHEN opportunity_date IS NOT NULL THEN 1 ELSE 0 END) AS opp_count,
           SUM(CASE WHEN lead_status='Closed_Won' THEN 1 ELSE 0 END) AS won_count
    FROM contacts
    WHERE mql_date IS NOT NULL
    GROUP BY SUBSTR(mql_date,1,7)
    ORDER BY cohort_month
    """
    df = pd.read_sql_query(sql, conn)
    df["mql_to_sql_rate"] = df["sql_count"] / df["cohort_size"].replace(0, np.nan)
    df["mql_to_opp_rate"] = df["opp_count"] / df["cohort_size"].replace(0, np.nan)
    df["mql_to_won_rate"] = df["won_count"] / df["cohort_size"].replace(0, np.nan)
    return df


def build_cohort_heatmap(conn) -> pd.DataFrame:
    """Returns a pivot table: cohort_month × months_since → conversion_rate."""
    contacts = pd.read_sql_query(
        "SELECT contact_id, SUBSTR(mql_date,1,7) AS cohort_month, "
        "mql_date, sql_date, sal_date, opportunity_date, closed_date, lead_status "
        "FROM contacts WHERE mql_date IS NOT NULL",
        conn
    )

    rows = []
    for _, c in contacts.iterrows():
        cohort = c["cohort_month"]
        mql_dt = pd.to_datetime(c["mql_date"])

        # At each month checkpoint, what was the cumulative conversion state?
        for m in range(0, 13):
            checkpoint = mql_dt + pd.DateOffset(months=m)
            sql_done = c["sql_date"] and pd.to_datetime(c["sql_date"]) <= checkpoint
            opp_done = c["opportunity_date"] and pd.to_datetime(c["opportunity_date"]) <= checkpoint
            won_done = c["lead_status"] == "Closed_Won" and c["closed_date"] and pd.to_datetime(c["closed_date"]) <= checkpoint

            rows.append({
                "cohort_month": cohort,
                "months_since": m,
                "contact_id":   c["contact_id"],
                "reached_sql":  int(bool(sql_done)),
                "reached_opp":  int(bool(opp_done)),
                "reached_won":  int(bool(won_done)),
            })

    long = pd.DataFrame(rows)
    heatmap = (
        long.groupby(["cohort_month", "months_since"])
            .agg(cohort_size=("contact_id", "nunique"),
                 sql_conv=("reached_sql", "sum"),
                 opp_conv=("reached_opp", "sum"),
                 won_conv=("reached_won", "sum"))
            .reset_index()
    )
    heatmap["sql_rate"] = heatmap["sql_conv"] / heatmap["cohort_size"]
    heatmap["opp_rate"] = heatmap["opp_conv"] / heatmap["cohort_size"]
    heatmap["won_rate"] = heatmap["won_conv"] / heatmap["cohort_size"]
    return heatmap


def build_channel_cohorts(conn) -> pd.DataFrame:
    sql = """
    WITH ft AS (
        SELECT contact_id, channel
        FROM (SELECT contact_id, channel,
                     ROW_NUMBER() OVER (PARTITION BY contact_id ORDER BY touchpoint_timestamp) AS rn
              FROM touchpoints) WHERE rn=1
    )
    SELECT ft.channel,
           COUNT(DISTINCT c.contact_id) AS cohort_size,
           COUNT(DISTINCT CASE WHEN c.mql_date IS NOT NULL THEN c.contact_id END) AS mql_count,
           COUNT(DISTINCT CASE WHEN c.opportunity_date IS NOT NULL THEN c.contact_id END) AS opp_count,
           COUNT(DISTINCT CASE WHEN c.lead_status='Closed_Won' THEN c.contact_id END) AS won_count,
           SUM(CASE WHEN o.closed_won=1 THEN o.amount ELSE 0 END) AS total_revenue
    FROM contacts c
    LEFT JOIN ft ON ft.contact_id = c.contact_id
    LEFT JOIN opportunities o ON o.primary_contact_id = c.contact_id
    WHERE ft.channel IS NOT NULL
    GROUP BY ft.channel
    """
    df = pd.read_sql_query(sql, conn)
    df["win_rate"]            = df["won_count"] / df["opp_count"].replace(0, np.nan)
    df["revenue_per_lead"]    = df["total_revenue"] / df["cohort_size"].replace(0, np.nan)
    return df.sort_values("won_count", ascending=False)


def run_all(conn=None) -> dict:
    if conn is None:
        conn = sqlite3.connect(config.DB_PATH)
    return {
        "acquisition_cohorts": build_acquisition_cohorts(conn),
        "channel_cohorts":     build_channel_cohorts(conn),
    }

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    conn = sqlite3.connect(config.DB_PATH)

    print("Running cohort analysis...")
    results = run_all(conn)

    print("\n--- Acquisition Cohorts (first 6) ---")
    print(results["acquisition_cohorts"].head(6).to_string(index=False))

    print("\n--- Channel Cohorts ---")
    print(results["channel_cohorts"].to_string(index=False))

    os.makedirs("sql", exist_ok=True)
    with open("sql/04_cohort_analysis.sql", "w") as f:
        f.write(COHORT_SQL)
    print("\n✓ sql/04_cohort_analysis.sql written")
    conn.close()


if __name__ == "__main__":
    main()
