
-- ==========================================================================
-- 04_cohort_analysis.sql
-- Cohort-based conversion and retention analysis.
-- ==========================================================================

-- --------------------------------------------------------------------------
-- Query 1: Monthly Acquisition Cohort Conversion Heatmap
-- Rows = MQL month, Columns = months since MQL (0-12)
-- Values = cumulative conversion rate to each stage.
-- --------------------------------------------------------------------------
WITH mqls AS (
    SELECT
        contact_id,
        account_id,
        SUBSTR(mql_date, 1, 7)          AS cohort_month,
        mql_date,
        sql_date,
        sal_date,
        opportunity_date,
        closed_date,
        lead_status
    FROM contacts
    WHERE mql_date IS NOT NULL
),
cohort_base AS (
    SELECT
        cohort_month,
        COUNT(*)                                                        AS cohort_size,
        SUM(CASE WHEN sql_date IS NOT NULL THEN 1 ELSE 0 END)           AS converted_sql,
        SUM(CASE WHEN opportunity_date IS NOT NULL THEN 1 ELSE 0 END)   AS converted_opp,
        SUM(CASE WHEN lead_status = 'Closed_Won' THEN 1 ELSE 0 END)    AS converted_won
    FROM mqls
    GROUP BY cohort_month
),
month_breakdown AS (
    SELECT
        m.cohort_month,
        CAST((JULIANDAY(m.sql_date) - JULIANDAY(m.mql_date)) / 30 AS INT) AS months_to_sql,
        CAST((JULIANDAY(m.opportunity_date) - JULIANDAY(m.mql_date)) / 30 AS INT) AS months_to_opp,
        CAST((JULIANDAY(m.closed_date) - JULIANDAY(m.mql_date)) / 30 AS INT) AS months_to_won
    FROM mqls m
    WHERE m.sql_date IS NOT NULL
)
SELECT cb.cohort_month, cb.cohort_size,
       ROUND(1.0 * cb.converted_sql / NULLIF(cb.cohort_size, 0), 4)  AS sql_conversion_rate,
       ROUND(1.0 * cb.converted_opp / NULLIF(cb.cohort_size, 0), 4)  AS opp_conversion_rate,
       ROUND(1.0 * cb.converted_won / NULLIF(cb.cohort_size, 0), 4)  AS won_conversion_rate
FROM cohort_base cb
ORDER BY cohort_month;

-- --------------------------------------------------------------------------
-- Query 2: Channel Cohort Comparison
-- Conversion rates by first-touch channel over 12 months.
-- --------------------------------------------------------------------------
WITH first_touch AS (
    SELECT contact_id,
           channel AS first_channel
    FROM (
        SELECT contact_id, channel,
               ROW_NUMBER() OVER (PARTITION BY contact_id ORDER BY touchpoint_timestamp) AS rn
        FROM touchpoints
    ) WHERE rn = 1
)
SELECT
    ft.first_channel                                                    AS channel,
    COUNT(DISTINCT c.contact_id)                                        AS cohort_size,
    COUNT(DISTINCT CASE WHEN c.mql_date  IS NOT NULL THEN c.contact_id END) AS mql_count,
    COUNT(DISTINCT CASE WHEN c.sql_date  IS NOT NULL THEN c.contact_id END) AS sql_count,
    COUNT(DISTINCT CASE WHEN c.opportunity_date IS NOT NULL
                        THEN c.contact_id END)                          AS opp_count,
    COUNT(DISTINCT CASE WHEN c.lead_status = 'Closed_Won'
                        THEN c.contact_id END)                          AS won_count,
    ROUND(1.0 * COUNT(DISTINCT CASE WHEN c.mql_date IS NOT NULL
                                    THEN c.contact_id END)
          / NULLIF(COUNT(DISTINCT c.contact_id), 0), 4)                 AS mql_rate,
    ROUND(1.0 * COUNT(DISTINCT CASE WHEN c.lead_status = 'Closed_Won'
                                    THEN c.contact_id END)
          / NULLIF(COUNT(DISTINCT CASE WHEN c.opportunity_date IS NOT NULL
                                       THEN c.contact_id END), 0), 4)   AS win_rate
FROM contacts c
LEFT JOIN first_touch ft ON ft.contact_id = c.contact_id
WHERE ft.first_channel IS NOT NULL
GROUP BY ft.first_channel
ORDER BY won_count DESC;

-- --------------------------------------------------------------------------
-- Query 3: Cohort Revenue Analysis
-- Revenue generated by each acquisition month cohort + payback period.
-- --------------------------------------------------------------------------
WITH cohort_revenue AS (
    SELECT
        SUBSTR(c.mql_date, 1, 7)       AS cohort_month,
        COUNT(DISTINCT c.contact_id)    AS cohort_size,
        SUM(CASE WHEN o.closed_won = 1 THEN o.amount ELSE 0 END) AS total_revenue,
        AVG(CASE WHEN o.closed_won = 1 THEN o.amount END)        AS avg_deal_size,
        COUNT(DISTINCT CASE WHEN o.closed_won = 1
                            THEN c.contact_id END)                AS won_contacts
    FROM contacts c
    LEFT JOIN opportunities o ON o.primary_contact_id = c.contact_id
    WHERE c.mql_date IS NOT NULL
    GROUP BY SUBSTR(c.mql_date, 1, 7)
)
SELECT
    cohort_month,
    cohort_size,
    total_revenue,
    ROUND(avg_deal_size, 0)            AS avg_deal_size,
    won_contacts,
    ROUND(1.0 * total_revenue / NULLIF(cohort_size, 0), 0) AS revenue_per_lead,
    SUM(total_revenue) OVER (ORDER BY cohort_month ROWS UNBOUNDED PRECEDING) AS cumulative_revenue
FROM cohort_revenue
ORDER BY cohort_month;

-- --------------------------------------------------------------------------
-- Query 4: Cohort Retention Curve
-- % of each cohort with at least one touchpoint in subsequent months.
-- --------------------------------------------------------------------------
WITH mql_cohorts AS (
    SELECT c.contact_id,
           SUBSTR(c.mql_date, 1, 7) AS cohort_month
    FROM contacts c
    WHERE c.mql_date IS NOT NULL
),
monthly_activity AS (
    SELECT t.contact_id,
           SUBSTR(t.touchpoint_timestamp, 1, 7) AS activity_month
    FROM touchpoints t
    GROUP BY t.contact_id, SUBSTR(t.touchpoint_timestamp, 1, 7)
)
SELECT
    mc.cohort_month,
    ma.activity_month,
    CAST((JULIANDAY(ma.activity_month || '-01') -
          JULIANDAY(mc.cohort_month || '-01')) / 30 AS INT) AS months_since,
    COUNT(DISTINCT mc.contact_id) AS cohort_size,
    COUNT(DISTINCT CASE WHEN ma.contact_id IS NOT NULL
                        THEN mc.contact_id END)             AS active_contacts,
    ROUND(1.0 * COUNT(DISTINCT CASE WHEN ma.contact_id IS NOT NULL
                                    THEN mc.contact_id END)
          / NULLIF(COUNT(DISTINCT mc.contact_id), 0), 4)   AS retention_rate
FROM mql_cohorts mc
LEFT JOIN monthly_activity ma ON ma.contact_id = mc.contact_id
    AND ma.activity_month >= mc.cohort_month
GROUP BY mc.cohort_month, ma.activity_month
HAVING months_since BETWEEN 0 AND 12
ORDER BY mc.cohort_month, months_since;
